### ISSUE TITLE
application file disappear from server after a couple of minutes

### ISSUE THREAD

**Issue by dagon84** [prasathmani/tinyfilemanager#273]
Issue:
- I upload the file Tinyfilmanager.php via FTP in a subfolder, file permission 644, folder permission 755
- I can browse for a couple of minutes in the interface
- After a while I get error 404
- I'm going to check the folder where i uploaded the file, and the file Tinyfilmanager.php is missing, as never uploaded.

is the only file that diasappear, i don't understand why.

Error log report the following

> Use of undefined constant FM_EXCLUDE_ITEMS - assumed 'FM_EXCLUDE_ITEMS' in /home/clsprplv/public_html/ipcam/tinyfilemanager.php on line 2248
> [31-Dec-2019 20:03:54 Etc/UTC] PHP Warning:  in_array() expects parameter 2 to be array, string given in /path/tinyfilemanager.php on line 2248

But I can't understand how to solve the error.

Am I missing some setting?
Any help would be appreciated. 

I have tried to copy the code ina  previous php file, that disappear after a while

**Comment by decioviegas** [comment]
Hello
I have the same problem. A Tinyfilmanager.php file contents disappear from server.
(the file Tinyfilmanager.php is empty after the first call)

**Comment by prasathmani** [comment]
@decioviegas  and @dagon84 ,
could you please check error logs and security logs, if you found something related to tinyfilemanager, plz share the logs, really it helps to find the root cause.

**Comment by decioviegas** [comment]
I have not error log.
Just open the login page and the file (Tinyfilmanager.php)  will be empty
![print](https://user-images.githubusercontent.com/59318411/71721824-83999b00-2e1e-11ea-8746-ba7228d7bb19.PNG)

**Comment by decioviegas** [comment]
The Immunify360 has detected "Original (infected) file will be removed" 
Reason: SMW-SA-05072-mlw-4	
Status: Content removed.

**Comment by k4mrul** [comment]
I am having the same issue. After log in, the contents of tinyfilemanager.php disappeared. Anyone know any workaround?

**Comment by skerbis** [comment]
in https://github.com/prasathmani/tinyfilemanager/issues/461 you can see more details.

**Comment by alisson-juns** [comment]
I have the same problem.
Did anyone get any solution?
My server deletes the file and there is no log on it.

**Comment by skerbis** [comment]
@alisson-juns whitelist this script, wait til it’s fixer or use for example a solution like https://github.com/icecoder/ICEcoder.

**Comment by attare026** [comment]
@prasathmani anyone solved this issue?

**Comment by skerbis** [comment]
@attare026 whitelist the script in your ImunifyAV

**Comment by alisson-juns** [comment]
I had to contact the technical support of my hosting to create an exception on the server so that the file was not deleted.

**Comment by attare026** [comment]
> whitelist the script in your ImunifyAV

can explain it how can I do?
thanks

**Comment by ueen** [comment]
same, the provider locked the entire site, maybe you should mention that in the README, its kind of a big deal!!

**Comment by prasathmani** [comment]
removed PHP decoded code in the new version, hope it resolves the issue

**Comment by saeed74** [comment]
isuue is not resolved yet in last version:
![Screenshot_583](https://user-images.githubusercontent.com/8604609/130323538-54aa286f-40bc-475f-8125-9651e5470fc6.png)

**Comment by dampelz** [comment]
same issue
SMW-SA-05072-php.tool.filemanager-7

**Comment by Hieung28** [comment]
has anyone solved this issue?

**Comment by saeed74** [comment]
this bug is still present in version  tiny file manager 2.4.7

**Comment by saeed74** [comment]
![Screenshot_43](https://user-images.githubusercontent.com/8604609/177575222-945bc550-9088-461f-9cb4-a16389d8a83b.png)

**Comment by FransW5** [comment]
Solution for cPanel firewall:

Open tinyfilemanager.php in a text editor And

Replace All:
`fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));
`
With:
`$FM_PATH=FM_PATH; fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));`

**Comment by YsrMe** [comment]
Hello...

the script was working fine on bluehost & hostinger hosting services, but after deploying the security feature the file was detected as malicious file & got deleted ⁉

i am very sad because this is the best file manager scripts that you can find so far... is there any progress on solving this issue ⁉

Regards,

**Comment by robsd** [comment]
I get the same issue "SMW-SA-05072-php.tool.filemanager-2".

File contents gets wiped after upload.

I've tried @FransW5's suggestion but that didn't work for me unfortunately.

**Comment by FransW5** [comment]
@robsd 

I tested on (cPanel 106.0.8 + cPGuard + imunify360 Malware scanner) and with the following replacement, solves the problem.

What hosting management system are you using?
What antivirus and firewall is running on your host?

```
Replace All:
fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));

With:
$FM_PATH=FM_PATH; fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));
```

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).

**Comment by YsrMe** [comment]
Hello...

Still the same issue on hostinger.com it sees it as (Malicious) file!

![image](https://user-images.githubusercontent.com/48659217/203923793-e1bd7ba1-8c17-4c9c-b321-4bf529b31d8f.png)

**Comment by Salkalkhan** [comment]
yes They are deleting instantly now. This single page file manager is awesome but can't run on Hostinger. Really need to do something quickly.

**Comment by prasathmani** [comment]
I am happy to fit it, but need more information what line or part of code is causing the problem.

**Comment by Salkalkhan** [comment]
I don't know which line is causing this problem as I have done many changes in Version 2.4.4 and It is working for me. Yesterday I updated the page and it disappear after few minutes. I re upload but again disappear. It was malware scanner from hostinger.com who keep deleting that file. 
Gave me sometime, Tomorrow I will download previous commits and Upload it One by one.

**Comment by Salkalkhan** [comment]
Can anyone confirm me

**Comment by Salkalkhan** [comment]
Winter Release 22 Latest  version = 2.5.0   8de16a4
deleting Line number 3085-3087 solves the deleting problem.  

```
if(is_array($contentType)) {
        $contentType = implode(' ', $contentType);
    }
```
Delete this above code.

**Comment by YsrMe** [comment]
Hello @Salkalkhan 

I did what you suggested & it is still the same issue as you can see below :(

![image](https://user-images.githubusercontent.com/48659217/204126795-fe1ac610-c458-4667-971b-f41f8432770d.png)

**Comment by Salkalkhan** [comment]
Hi, I don't know why it didn't got deleted within an hour but when Today I logged in my server it was deleted. 
I have left with only those files which were released before Feb 14 2022.
I am still working to find the exact code which is causing this issue. Problem is they are not deleting instantly. After making any changes have to wait for them to delete that file. 


My suggestion will be to go to commit and download any version which was uploaded before feb 14 this year and work till any solution is released.

**Comment by prasathmani** [comment]
duplicate #1067
